// Comprehensive Seed Dataset mirroring database/seed.sql

const memberships = [
  { id: 1, tier_name: 'Basic Explorer', min_points: 0, discount_pct: 0, points_multiplier: 1.0, perks_description: 'Standard access, 1 pt per ₹100' },
  { id: 2, tier_name: 'Silver Voyager', min_points: 250, discount_pct: 5, points_multiplier: 1.25, perks_description: '5% discount on select bookings, 1.25x pts' },
  { id: 3, tier_name: 'Gold Elite', min_points: 750, discount_pct: 10, points_multiplier: 1.5, perks_description: '10% discount, 1.5x pts, priority support' },
  { id: 4, tier_name: 'Platinum Concierge', min_points: 1500, discount_pct: 15, points_multiplier: 2.0, perks_description: '15% VIP discount, 2.0x pts, 24/7 concierge' }
];

const users = [
  {
    id: 1,
    membership_id: 4,
    full_name: 'Aarav Sharma (Admin)',
    email: 'admin@booksphere.com',
    password: 'password123',
    phone: '+91 98201 12345',
    reward_points: 2450,
    avatar_url: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=200&q=80',
    role: 'super_admin'
  },
  {
    id: 2,
    membership_id: 3,
    full_name: 'Priya Nair',
    email: 'priya.nair@example.com',
    password: 'password123',
    phone: '+91 98450 67890',
    reward_points: 890,
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80',
    role: 'user'
  },
  {
    id: 3,
    membership_id: 2,
    full_name: 'Rohan Verma',
    email: 'rohan.verma@example.com',
    password: 'password123',
    phone: '+91 97110 34567',
    reward_points: 410,
    avatar_url: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=200&q=80',
    role: 'user'
  },
  {
    id: 4,
    membership_id: 1,
    full_name: 'Ananya Deshmukh',
    email: 'ananya.d@example.com',
    password: 'password123',
    phone: '+91 99300 89123',
    reward_points: 180,
    avatar_url: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=200&q=80',
    role: 'user'
  },
  {
    id: 5,
    membership_id: 3,
    full_name: 'Vikramaditya Rao',
    email: 'vikram.rao@example.com',
    password: 'password123',
    phone: '+91 96190 45678',
    reward_points: 920,
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    role: 'admin'
  }
];

const categories = [
  { id: 1, name: 'Express Bus', slug: 'bus', parent_type: 'TRANSPORT', icon_name: 'Bus', description: 'Luxury Sleeper and AC coaches' },
  { id: 2, name: 'High-Speed Rail', slug: 'train', parent_type: 'TRANSPORT', icon_name: 'Train', description: 'Vande Bharat & Tejas express' },
  { id: 3, name: 'Domestic Flights', slug: 'flight', parent_type: 'TRANSPORT', icon_name: 'Plane', description: 'Non-stop metro flights' },
  { id: 4, name: 'Chauffeur Cab', slug: 'cab', parent_type: 'TRANSPORT', icon_name: 'Car', description: 'Intercity and airport transfers' },
  { id: 5, name: 'Blockbuster Movies', slug: 'movie', parent_type: 'ENTERTAINMENT', icon_name: 'Film', description: 'IMAX 3D and 4DX screens' },
  { id: 6, name: 'Standup Comedy', slug: 'comedy', parent_type: 'ENTERTAINMENT', icon_name: 'Mic', description: 'Live standup specials' },
  { id: 7, name: 'Live Music & Concerts', slug: 'concert', parent_type: 'ENTERTAINMENT', icon_name: 'Music', description: 'Stadium tours and music festivals' },
  { id: 8, name: 'Theatre & Drama', slug: 'theatre', parent_type: 'ENTERTAINMENT', icon_name: 'Drama', description: 'Award-winning plays and musicals' },
  { id: 9, name: 'Football & Box Turf', slug: 'turf', parent_type: 'SPORTS', icon_name: 'Trophy', description: 'FIFA approved 5v5 & 7v7 turf' },
  { id: 10, name: 'Olympic Swimming Pool', slug: 'pool', parent_type: 'SPORTS', icon_name: 'Waves', description: 'Heated 50m lap swimming slots' },
  { id: 11, name: 'Cricket Grounds', slug: 'ground', parent_type: 'SPORTS', icon_name: 'Shield', description: 'Floodlit cricket grounds with pavilion' },
  { id: 12, name: 'Badminton & Tennis', slug: 'court', parent_type: 'SPORTS', icon_name: 'Activity', description: 'Indoor wooden and synthetic courts' },
  { id: 13, name: 'Luxury Hotels & Villas', slug: 'hotel', parent_type: 'HOTEL', icon_name: 'Building', description: '5-star boutique stays and pool villas' },
  { id: 14, name: 'Fine Dining & Rooftops', slug: 'restaurant', parent_type: 'RESTAURANT', icon_name: 'Utensils', description: 'Rooftop lounges and chef dining' },
  { id: 15, name: 'Theme & Amusement Parks', slug: 'themepark', parent_type: 'EXPERIENCE', icon_name: 'Sparkles', description: 'High-thrill rollercoasters and waterparks' }
];

const locations = [
  { id: 1, city: 'Mumbai', state: 'Maharashtra', country: 'India', landmark: 'BKC / Nariman Point' },
  { id: 2, city: 'Pune', state: 'Maharashtra', country: 'India', landmark: 'Koregaon Park' },
  { id: 3, city: 'Bengaluru', state: 'Karnataka', country: 'India', landmark: 'Indiranagar / MG Road' },
  { id: 4, city: 'Delhi NCR', state: 'Delhi', country: 'India', landmark: 'Connaught Place / Cyber City' },
  { id: 5, city: 'Goa', state: 'Goa', country: 'India', landmark: 'Calangute / Vagator' },
  { id: 6, city: 'Hyderabad', state: 'Telangana', country: 'India', landmark: 'Gachibowli / HITEC City' },
  { id: 7, city: 'Chennai', state: 'Tamil Nadu', country: 'India', landmark: 'ECR / Marina' }
];

const services = [
  {
    id: 1,
    category_id: 3,
    category_slug: 'flight',
    parent_type: 'TRANSPORT',
    location_id: 1,
    city: 'Mumbai',
    title: 'SkyWings Air — Mumbai to Bengaluru',
    slug: 'skywings-bom-blr',
    tagline: 'Luxury Boeing 787 Dreamliner Non-Stop',
    description: 'Non-stop ultra-smooth flight with complimentary gourmet meal, 25kg luggage allowance, and high-speed Wi-Fi onboard.',
    cover_image: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=800&q=80',
    base_price: 4499,
    price_unit: 'per seat',
    rating: 4.85,
    review_count: 342,
    capacity_total: 180,
    status: 'active',
    is_featured: true,
    amenities: ['In-Flight Wi-Fi', 'Gourmet Hot Meal', '25kg Baggage', 'USB Fast Charging']
  },
  {
    id: 2,
    category_id: 2,
    category_slug: 'train',
    parent_type: 'TRANSPORT',
    location_id: 1,
    city: 'Mumbai',
    title: 'Vande Bharat Express — Mumbai to Pune (VistaDome)',
    slug: 'vande-bharat-bom-pune',
    tagline: 'High Speed Panoramic Western Ghats Cruise',
    description: 'Experience 160 km/h cruising through scenic Bhor Ghat tunnels with 180-degree rotating plush leather seats and executive dining.',
    cover_image: 'https://images.unsplash.com/photo-1532103054090-a3392330ec55?auto=format&fit=crop&w=800&q=80',
    base_price: 780,
    price_unit: 'per passenger',
    rating: 4.90,
    review_count: 520,
    capacity_total: 112,
    status: 'active',
    is_featured: true,
    amenities: ['180° Rotating Seats', 'Executive Breakfast', 'Panoramic Windows', 'Onboard Infotainment']
  },
  {
    id: 3,
    category_id: 1,
    category_slug: 'bus',
    parent_type: 'TRANSPORT',
    location_id: 2,
    city: 'Pune',
    title: 'IntrCity SmartBus — Pune to Goa Sleeper',
    slug: 'intrcity-pune-goa',
    tagline: 'Safe, Sanitized AC Sleeper with Onboard Washroom',
    description: 'Private double and single pods with high-density mattress, personal infotainment tablet, charging ports, and certified safety crew.',
    cover_image: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=800&q=80',
    base_price: 1150,
    price_unit: 'per berth',
    rating: 4.72,
    review_count: 189,
    capacity_total: 36,
    status: 'active',
    is_featured: false,
    amenities: ['Individual AC Pod', 'Washroom Onboard', 'Blanket & Pillow', 'GPS Live Tracking']
  },
  {
    id: 4,
    category_id: 4,
    category_slug: 'cab',
    parent_type: 'TRANSPORT',
    location_id: 1,
    city: 'Mumbai',
    title: 'UrbanDrive Premium Chauffeur Sedan',
    slug: 'urbandrive-cab-mumbai',
    tagline: 'Airport & Intercity Chauffeur Driven Mercedes / Crysta',
    description: 'Executive chauffeured vehicles with sanitized leather interiors, chilled mineral water, Wi-Fi, and 100% on-time guarantee.',
    cover_image: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80',
    base_price: 2800,
    price_unit: 'per trip',
    rating: 4.80,
    review_count: 145,
    capacity_total: 20,
    status: 'active',
    is_featured: false,
    amenities: ['Chauffeur Uniformed', 'Bottled Mineral Water', 'Live GPS Tracking', 'Zero Surge Pricing']
  },
  {
    id: 6,
    category_id: 5,
    category_slug: 'movie',
    parent_type: 'ENTERTAINMENT',
    location_id: 1,
    city: 'Mumbai',
    title: 'PVR INOX IMAX with Laser — Avatar & Oppenheimer',
    slug: 'imax-laser-mumbai',
    tagline: 'Giant 1.43:1 Screen with 12-Channel Dolby Atmos',
    description: 'Experience pure cinema mastery with ultra-crisp 4K dual laser projection, electric motorized leather recliners, and in-seat gourmet dining.',
    cover_image: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=800&q=80',
    base_price: 480,
    price_unit: 'per ticket',
    rating: 4.92,
    review_count: 610,
    capacity_total: 240,
    status: 'active',
    is_featured: true,
    amenities: ['IMAX 4K Laser', 'Dolby Atmos 12-Channel', 'Plush Recliner', 'In-Seat Butler']
  },
  {
    id: 7,
    category_id: 6,
    category_slug: 'comedy',
    parent_type: 'ENTERTAINMENT',
    location_id: 3,
    city: 'Bengaluru',
    title: 'Zakir Khan Live — "Tathastu" Arena Tour',
    slug: 'zakir-khan-live-blr',
    tagline: '2 Hours of Non-stop Heartfelt & Relatable Laughs',
    description: 'The Sakht Launda returns with his blockbuster stadium comedy special filled with nostalgia, relatable punchlines, and storytelling.',
    cover_image: 'https://images.unsplash.com/photo-1585699324551-f6c309eedeca?auto=format&fit=crop&w=800&q=80',
    base_price: 1299,
    price_unit: 'per seat',
    rating: 4.95,
    review_count: 870,
    capacity_total: 1200,
    status: 'active',
    is_featured: true,
    amenities: ['Auditorium Seating', 'Live Stage Lighting', 'Parking Available', 'Air Conditioned']
  },
  {
    id: 8,
    category_id: 7,
    category_slug: 'concert',
    parent_type: 'ENTERTAINMENT',
    location_id: 1,
    city: 'Mumbai',
    title: 'Sunburn Arena — Martin Garrix World Tour',
    slug: 'sunburn-garrix-mumbai',
    tagline: 'Epic Lasers, Pyrotechnics & World #1 DJ in Mumbai',
    description: 'The premier electronic music festival at Mahalaxmi Racecourse featuring cutting-edge LED stages, fireworks, and international openers.',
    cover_image: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=800&q=80',
    base_price: 2499,
    price_unit: 'per pass',
    rating: 4.88,
    review_count: 1420,
    capacity_total: 5000,
    status: 'active',
    is_featured: true,
    amenities: ['VIP Lounge Area', 'F&B Food Trucks', 'Entry Wristband', 'Medical Booths']
  },
  {
    id: 10,
    category_id: 9,
    category_slug: 'turf',
    parent_type: 'SPORTS',
    location_id: 1,
    city: 'Mumbai',
    title: 'KickOff Pro 7v7 FIFA AstroTurf BKC',
    slug: 'kickoff-7v7-turf-bkc',
    tagline: 'Floodlit Brazilian AstroTurf with Dugouts & Showers',
    description: 'Premium 50mm shock-absorbent artificial grass turf with night floodlights, bibs, tournament footballs, and fresh shower facilities.',
    cover_image: 'https://images.unsplash.com/photo-1529900244469-990ff95a23f4?auto=format&fit=crop&w=800&q=80',
    base_price: 1400,
    price_unit: 'per hour',
    rating: 4.86,
    review_count: 230,
    capacity_total: 24,
    status: 'active',
    is_featured: true,
    amenities: ['FIFA Grade Turf', 'High-Beam Floodlights', 'Showers & Lockers', 'Free Match Balls & Bibs']
  },
  {
    id: 11,
    category_id: 10,
    category_slug: 'pool',
    parent_type: 'SPORTS',
    location_id: 3,
    city: 'Bengaluru',
    title: 'Aquatica Olympic Temperature-Controlled Lap Pool',
    slug: 'aquatica-pool-blr',
    tagline: 'Fina Standard 50m Ozone-Treated Swimming Arena',
    description: 'Pristine crystal-clear waters maintained at optimal 26°C with electronic touchpads, trained certified lifeguards, and sauna lounge.',
    cover_image: 'https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?auto=format&fit=crop&w=800&q=80',
    base_price: 450,
    price_unit: 'per 90-min slot',
    rating: 4.79,
    review_count: 175,
    capacity_total: 30,
    status: 'active',
    is_featured: false,
    amenities: ['Heated Pool 26°C', 'Certified Lifeguards', 'Steam & Sauna Room', 'Lockers Provided']
  },
  {
    id: 13,
    category_id: 12,
    category_slug: 'court',
    parent_type: 'SPORTS',
    location_id: 6,
    city: 'Hyderabad',
    title: 'Gachibowli Badminton Academy — Teakwood Courts',
    slug: 'gachibowli-badminton-courts',
    tagline: 'BWF Approved 4-Court Badminton Complex with AC',
    description: 'High-grip Yonex approved wooden courts with glare-free overhead LED lighting, Yonex shuttlecock dispenser, and warm-up track.',
    cover_image: 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?auto=format&fit=crop&w=800&q=80',
    base_price: 600,
    price_unit: 'per court/hr',
    rating: 4.82,
    review_count: 192,
    capacity_total: 16,
    status: 'active',
    is_featured: false,
    amenities: ['Teakwood Flooring', 'Air Conditioned', 'Yonex Racquet Rental', 'Shower Amenities']
  },
  {
    id: 14,
    category_id: 13,
    category_slug: 'hotel',
    parent_type: 'HOTEL',
    location_id: 5,
    city: 'Goa',
    title: 'The Azure Bay Cliffside Pool Villa — North Goa',
    slug: 'azure-bay-villa-goa',
    tagline: 'Private Infinity Pool Overlooking the Arabian Sea',
    description: 'Exclusive 3-bedroom luxury villa perched atop Vagator cliffs with private butler, sunset deck, jacuzzi, and complimentary brunch.',
    cover_image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80',
    base_price: 14999,
    price_unit: 'per night',
    rating: 4.96,
    review_count: 215,
    capacity_total: 8,
    status: 'active',
    is_featured: true,
    amenities: ['Private Infinity Pool', '24/7 Dedicated Butler', 'Sea-Facing Deck', 'Chef Prepared Breakfast']
  },
  {
    id: 15,
    category_id: 13,
    category_slug: 'hotel',
    parent_type: 'HOTEL',
    location_id: 1,
    city: 'Mumbai',
    title: 'The Grand Palace Heritage Suite — Colaba Mumbai',
    slug: 'grand-palace-mumbai',
    tagline: 'Colonial Elegance with 21st Century High-Tech Comforts',
    description: 'Spacious royal suites with Italian marble baths, sea-view balcony, 24-hour concierge, and private marina yacht access.',
    cover_image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80',
    base_price: 18500,
    price_unit: 'per night',
    rating: 4.93,
    review_count: 380,
    capacity_total: 25,
    status: 'active',
    is_featured: true,
    amenities: ['Sea-View Balcony', 'Spa & Wellness', 'Valet Parking', 'Luxury Airport Pickup']
  },
  {
    id: 17,
    category_id: 14,
    category_slug: 'restaurant',
    parent_type: 'RESTAURANT',
    location_id: 1,
    city: 'Mumbai',
    title: 'Celeste Sky Lounge & Pan-Asian Bistro Mumbai',
    slug: 'celeste-sky-lounge-mumbai',
    tagline: '36th Floor Panoramic Marine Drive Views & Signature Cocktails',
    description: 'Exquisite artisanal dim sum, robata grills, and molecular mixology set against the glittering backdrop of the Queen’s Necklace.',
    cover_image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80',
    base_price: 1500,
    price_unit: 'table cover deposit',
    rating: 4.89,
    review_count: 430,
    capacity_total: 20,
    status: 'active',
    is_featured: true,
    amenities: ['360° Skyline View', 'Live DJ & Saxophone', 'Valet Parking', 'Signature Cocktails']
  },
  {
    id: 19,
    category_id: 15,
    category_slug: 'themepark',
    parent_type: 'EXPERIENCE',
    location_id: 3,
    city: 'Bengaluru',
    title: 'Wonderla Amusement & Thrill Water Park',
    slug: 'wonderla-bangalore',
    tagline: '60+ International Grade High-G Thrill Rides',
    description: 'India’s #1 amusement park featuring Recoil reverse roller coaster, massive dual wave pools, high-speed water slides, and laser shows.',
    cover_image: 'https://images.unsplash.com/photo-1513889961551-628c1e5e2ee9?auto=format&fit=crop&w=800&q=80',
    base_price: 1350,
    price_unit: 'fast track pass',
    rating: 4.84,
    review_count: 980,
    capacity_total: 2000,
    status: 'active',
    is_featured: true,
    amenities: ['Fast-Track Queues', 'Locker & Costume Facility', 'Food Court Buffets', 'Multi-Level Wave Pools']
  },
  {
    id: 20,
    category_id: 15,
    category_slug: 'themepark',
    parent_type: 'EXPERIENCE',
    location_id: 5,
    city: 'Goa',
    title: 'Grand Island Scuba Diving & Dolphin Cruise Goa',
    slug: 'scuba-diving-goa',
    tagline: 'PADI Certified Underwater Exploration with HD Video',
    description: 'Sail out into turquoise Arabian Sea waters, explore living coral reefs, shipwrecks, and swim alongside wild spinner dolphins.',
    cover_image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80',
    base_price: 3200,
    price_unit: 'per diver',
    rating: 4.87,
    review_count: 340,
    capacity_total: 40,
    status: 'active',
    is_featured: true,
    amenities: ['PADI Dive Master Guide', 'Free Underwater 4K Video', 'Island BBQ Lunch', 'Snorkeling Gear Included']
  }
];

const coupons = [
  { id: 1, code: 'WELCOME10', description: '10% instant discount on your first booking', discount_type: 'PERCENTAGE', discount_value: 10, min_spend: 500, max_discount: 500, times_used: 142, is_active: true },
  { id: 2, code: 'FIRSTBOOK', description: 'Flat ₹200 off for first-time BookSphere explorers', discount_type: 'FIXED_AMOUNT', discount_value: 200, min_spend: 800, max_discount: 200, times_used: 89, is_active: true },
  { id: 3, code: 'SPORTS20', description: '20% off on all turfs, courts, and swimming pools', discount_type: 'PERCENTAGE', discount_value: 20, min_spend: 1000, max_discount: 400, times_used: 63, is_active: true },
  { id: 4, code: 'MOVIE50', description: '50% off on movie tickets up to ₹150', discount_type: 'PERCENTAGE', discount_value: 50, min_spend: 300, max_discount: 150, times_used: 210, is_active: true },
  { id: 5, code: 'LUXURYSTAY', description: 'Flat ₹1,500 off on premium villa stays', discount_type: 'FIXED_AMOUNT', discount_value: 1500, min_spend: 10000, max_discount: 1500, times_used: 27, is_active: true }
];

const bookings = [
  {
    id: 1,
    booking_ref: 'BK-2026-90112',
    user_id: 2,
    service_id: 6,
    service_title: 'PVR INOX IMAX with Laser — Avatar & Oppenheimer',
    booking_type: 'ENTERTAINMENT',
    booking_date: '2026-09-01',
    scheduled_date: '2026-09-10',
    scheduled_time: '07:30 PM',
    guest_count: 2,
    selected_seats: ['A3', 'A4'],
    base_amount: 960.00,
    discount_amount: 96.00,
    tax_amount: 155.52,
    service_fee: 40.00,
    final_amount: 1059.52,
    status: 'confirmed',
    qr_code_token: 'QR_BK90112_VERIFIED',
    customer_name: 'Priya Nair',
    customer_email: 'priya.nair@example.com',
    payment_method: 'UPI',
    created_at: '2026-09-01T14:32:00Z'
  },
  {
    id: 2,
    booking_ref: 'BK-2026-90245',
    user_id: 3,
    service_id: 10,
    service_title: 'KickOff Pro 7v7 FIFA AstroTurf BKC',
    booking_type: 'SPORTS',
    booking_date: '2026-09-02',
    scheduled_date: '2026-09-12',
    scheduled_time: '07:00 PM - 08:00 PM',
    guest_count: 10,
    selected_seats: ['SLOT 19:00-20:00'],
    base_amount: 1400.00,
    discount_amount: 200.00,
    tax_amount: 216.00,
    service_fee: 50.00,
    final_amount: 1466.00,
    status: 'confirmed',
    qr_code_token: 'QR_BK90245_VERIFIED',
    customer_name: 'Rohan Verma',
    customer_email: 'rohan.verma@example.com',
    payment_method: 'CREDIT_CARD',
    created_at: '2026-09-02T10:15:00Z'
  },
  {
    id: 3,
    booking_ref: 'BK-2026-89801',
    user_id: 2,
    service_id: 14,
    service_title: 'The Azure Bay Cliffside Pool Villa — North Goa',
    booking_type: 'HOTEL',
    booking_date: '2026-08-25',
    scheduled_date: '2026-09-20',
    scheduled_time: 'Check-in: 02:00 PM',
    guest_count: 2,
    selected_seats: ['Ocean Cliff Villa'],
    base_amount: 14999.00,
    discount_amount: 1500.00,
    tax_amount: 2429.82,
    service_fee: 250.00,
    final_amount: 16178.82,
    status: 'confirmed',
    qr_code_token: 'QR_BK89801_VERIFIED',
    customer_name: 'Priya Nair',
    customer_email: 'priya.nair@example.com',
    payment_method: 'NET_BANKING',
    created_at: '2026-08-25T18:40:00Z'
  },
  {
    id: 4,
    booking_ref: 'BK-2026-88410',
    user_id: 4,
    service_id: 1,
    service_title: 'SkyWings Air — Mumbai to Bengaluru',
    booking_type: 'TRANSPORT',
    booking_date: '2026-08-15',
    scheduled_date: '2026-08-20',
    scheduled_time: '09:15 AM',
    guest_count: 1,
    selected_seats: ['10A'],
    base_amount: 4499.00,
    discount_amount: 449.90,
    tax_amount: 728.84,
    service_fee: 100.00,
    final_amount: 4877.94,
    status: 'completed',
    qr_code_token: 'QR_BK88410_VERIFIED',
    customer_name: 'Ananya Deshmukh',
    customer_email: 'ananya.d@example.com',
    payment_method: 'UPI',
    created_at: '2026-08-15T08:20:00Z'
  },
  {
    id: 5,
    booking_ref: 'BK-2026-87905',
    user_id: 2,
    service_id: 17,
    service_title: 'Celeste Sky Lounge & Pan-Asian Bistro Mumbai',
    booking_type: 'RESTAURANT',
    booking_date: '2026-08-10',
    scheduled_date: '2026-08-14',
    scheduled_time: '08:30 PM',
    guest_count: 4,
    selected_seats: ['Table T-01 Window'],
    base_amount: 1500.00,
    discount_amount: 0.00,
    tax_amount: 270.00,
    service_fee: 50.00,
    final_amount: 1820.00,
    status: 'cancelled',
    qr_code_token: 'QR_BK87905_CANCELLED',
    customer_name: 'Priya Nair',
    customer_email: 'priya.nair@example.com',
    payment_method: 'CREDIT_CARD',
    created_at: '2026-08-10T19:10:00Z'
  },
  {
    id: 6,
    booking_ref: 'BK-2026-95400',
    user_id: 1,
    service_id: 1,
    service_title: 'SkyWings Air — Mumbai to Delhi (Executive Suite)',
    booking_type: 'TRANSPORT',
    booking_date: '2026-09-05',
    scheduled_date: '2026-09-18',
    scheduled_time: '10:30 AM',
    guest_count: 1,
    selected_seats: ['1A (First Class)'],
    base_amount: 8500.00,
    discount_amount: 850.00,
    tax_amount: 1377.00,
    service_fee: 100.00,
    final_amount: 9127.00,
    status: 'confirmed',
    qr_code_token: 'QR_BK95400_VERIFIED',
    customer_name: 'Rajeev Sharma',
    customer_email: 'admin@booksphere.com',
    payment_method: 'UPI',
    created_at: '2026-09-05T09:00:00Z'
  }
];

const auditLogs = [
  { id: 1, user_id: 1, action_type: 'INITIALIZE_SYSTEM', entity_name: 'system', entity_id: '0', details: { note: 'System schema booted with 25 tables' }, created_at: '2026-09-01T00:00:00Z' },
  { id: 2, user_id: 2, action_type: 'CONFIRM_BOOKING', entity_name: 'bookings', entity_id: '1', details: { amount: 1059.52, ref: 'BK-2026-90112' }, created_at: '2026-09-01T14:32:00Z' },
  { id: 3, user_id: 3, action_type: 'CONFIRM_BOOKING', entity_name: 'bookings', entity_id: '2', details: { amount: 1466.00, ref: 'BK-2026-90245' }, created_at: '2026-09-02T10:15:00Z' },
  { id: 4, user_id: 2, action_type: 'CANCEL_BOOKING', entity_name: 'bookings', entity_id: '5', details: { refund_amount: 1638.00, fee: 182.00 }, created_at: '2026-08-11T11:30:00Z' }
];

const reviews = [
  { id: 1, service_id: 6, user_id: 2, user_name: 'Priya Nair', rating: 5, review_text: 'Phenomenal IMAX laser clarity! Dual recliner seats and the sound mix made Oppenheimer breathtaking.', created_at: '2026-09-02' },
  { id: 2, service_id: 10, user_id: 3, user_name: 'Rohan Verma', rating: 5, review_text: 'Best 7v7 turf in BKC Mumbai. Soft non-abrasive turf, high-intensity floodlights, and clean change rooms.', created_at: '2026-09-03' },
  { id: 3, service_id: 1, user_id: 4, user_name: 'Ananya Deshmukh', rating: 5, review_text: 'Punctual, super comfortable Dreamliner flight with tasty hot meal and speedy baggage delivery in Bengaluru.', created_at: '2026-08-21' },
  { id: 4, service_id: 14, user_id: 5, user_name: 'Vikramaditya Rao', rating: 5, review_text: 'The private infinity plunge pool over Vagator cliffs in Goa is worth every penny. Butler service was world-class.', created_at: '2026-08-28' }
];

const notifications = [
  { id: 1, user_id: 2, title: 'Booking Confirmed! 🎉', message: 'Your reservation BK-2026-90112 is confirmed. Tap to view pass & QR ticket.', notification_type: 'BOOKING', is_read: false, created_at: '2026-09-01T14:32:00Z' },
  { id: 2, user_id: 3, title: 'Turf Slot Reserved', message: '7v7 Football match slot confirmed for BKC Arena. See you on the pitch!', notification_type: 'BOOKING', is_read: true, created_at: '2026-09-02T10:15:00Z' },
  { id: 3, user_id: 2, title: 'Refund Processed ₹1,638', message: 'Your refund for Booking BK-2026-87905 has been transferred to your original payment method.', notification_type: 'REFUND', is_read: false, created_at: '2026-08-11T11:30:00Z' },
  { id: 4, user_id: 2, title: 'Loyalty Upgrade: Gold Elite!', message: 'You have earned over 750 reward points. Enjoy 10% instant discounts on upcoming bookings.', notification_type: 'REWARDS', is_read: false, created_at: '2026-09-03T18:00:00Z' }
];

module.exports = {
  memberships,
  users,
  categories,
  locations,
  services,
  coupons,
  bookings,
  auditLogs,
  reviews,
  notifications
};
